<?php

namespace AppBundle\Repository;

/**
 * ServiceProviderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceProviderRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByActiveAndNotRemoved()
    {
        return $this->createQueryBuilder('sp')
            ->andWhere('sp.active = true')
            ->andWhere('sp.removedBy is null')
            ->andWhere('sp.removedOn is null')
//            ->setParameter('isActive',true)
            ;
    }

}
